---
title: '王家奕简历'
author: '王家奕'
date: '2021-08-01'
slug: resume-CH
categories: []
tags: []
layout: post
math: no
---

##### 邮箱： jiayiwang.2020@mitb.smu.edu.sg 
##### 手机： +65 89424295
##### 领英： [linkedin.com/in/jiayi-wang-smu](linkedin.com/in/jiayi-wang-smu)

# 教育背景

* **新加坡管理大学** [2020.8 - 2021.12] 

  * 商务信息学硕士 (数据分析)

  * 主修： Python, R, Tableau, 区块链, 数据库

* **厦门大学** [2015.9 - 2019.7] 

  * 通信工程
  
  * 主修: Arduino, C, Altium Design, Matlab

# 实习经离

* **UOB 大华银行核心技术部** - 新加坡 [2021.6 - 2021.12]

  * 数据分析实习生

  * 使用Python工具提取pdf内容并识别、自动更正银行合同中的错误

  * 检查不同国家 Linux 服务器的用户验收测试 (UAT) 和系统集成测试 (SIT) 以及这些数据库中的记录

* **中国移动浙江分公司** - 中国 [2015.6 - 2015.9]

  * 销售部门实习生组长

  * 使用微软工具可视化每日sim卡销售数据，并为不同实习生分配不同的销售任务
  
  * 获得最高销售奖

  * 组织了一场慈善义卖活动，并协调向当地学校图书馆捐赠了 2000 元人民币
  
# [项目经验](https://datavisual-wjy.netlify.app/)

* Python 分析 [2021.1 - 2021.4]

  * 编程 Python 代码来提取和处理美国总统 2 次演讲的数据

  * 通过正则表达式发现差异并可视化结果

* Arduino Cat-feeding device设计 [2021.1 - 2021.4]

  * 设计了可记录宠物健康状况的喂食装置
  
  * 编程代码，调试并上传到芯片（Arduino UNO）

* PUBG 游戏数据分析 (R语言) [2020.10 - 2020.11]

  * 分析超过100万玩家的游戏记录，向新玩家推荐着陆位置、武器选择和白圈预测
  
  * 实现着陆面积vs.存活率算法设计和大数据分析可视化

* 全国大学生电子设计大赛 [2017.10 - 2017.11]

  * 带领一组 3 名队友参加为期一周的电子设计大赛，并创造了一辆完全自主启动的充电车

  * 通过使用磁铁提高充电效率，可以提高电源传输效率

* Arduino自动浇水机设计 [2017.5 - 2017.6] 

  * 获得学院创意大赛三等奖

  * 基于Arduino UNO，编写主要功能代码

* 图片识别猜拳游戏 (MATLAB) [2016.9 - 2016.11] 

  * 编写MATLAB项目，通过区分输入图片来预测猜手指游戏的结果

  * 改进算法以通过机器学习获得更准确的结果。
  
# 其他

* 技术技能：Python、R、Tableau、C、MySQL、JMP、SAS、Arduino、MATLAB

* 语言：普通话、英语、杭州方言

* 课外活动：厦门大学学生会副部长

* 志愿者工作：厦门金砖国家会议志愿者

* 兴趣：摄影、图像编辑