---
title: 'Jiayi Wang-Resume'
author: 'Jiayi Wang'
date: '2021-08-09'
slug: resume-en
categories: []
tags: []
layout: post
math: no
---

##### jiayiwang.2020@mitb.smu.edu.sg 
##### +65 89424295
##### [linkedin.com/in/jiayi-wang-smu](linkedin.com/in/jiayi-wang-smu)

# EDUCATION

* **SINGAPORE MANAGEMENT UNIVERSITY** [Aug 2020- Dec 2021] 

  * Master of IT in Business (Analytics Track)

  * Modules: Python, R, Tableau, Blockchain, MySQL

* **Xiamen University, China** [Sep 2015 - Jul 2019] 

  * Bachelor in Communication Engineering 
  
  * Modules: Arduino, C, Altium Design, Matlab

# EXPERIENCE

* **UOB Group Banking Technology – Core Banking** - Singapore [Jun 2021 -Dec 2021]

  * Data Analysis Intern 

  * Using Python tools to automatically correct errors in bank contracts

  * Checking User Acceptance Testing (UAT) and System Integration Testing (SIT) in different countries' Linux servers and records in those database

* **China Mobile** - China [Jul 2015 -Sep 2015]

  * Sales Intern 

  * Used Microsoft Tools to visualize daily sim card sales data and allocated different selling tasks to best sellers
  
  * Achieved top sales award

  * Organized a charity sale in and coordinated donations of RMB2000 (S$400) to a local school library
  
# [ACADEMIC PROJECTS](https://datavisual-wjy.netlify.app/)

* Python analysis (Python) (Jan 2021 - Apr 2021)

  * Programed Python codes to extract and process data from 2 speeches of U.S.A presidents

  * Found the differences by Regular Expression and visualized the results

* Design of Arduino Cat-feeding device (C) (Jan 2021 - Apr 2021)

  * Designed a feeding device which can record the health of pets
  
  * Programed codes, debug it and upload to the chip (Arduino UNO )

* PUBG game data analysis (R) (Oct 2020 - Nov 2020)

  * Analyzed over 1 million players’ game records and drove recommendations on landing location, weapon choice and white circle prediction to new players
  
  * Achieved landing area vs. survive rate algorithm design and big data analysis visualization

* National Undergraduate Electronics Design Contest (Oct 2017 - Nov 2017)

  * Led a group of 3 teammates in a week-long Electronics Design Contest and created a fully autonomic charging car

  * Improved the charging efficiency by use of magnets, which could improve the amount of transition

* Design of Arduino automatically watering machine (May 2017 - Jun 2017)

  * Won the 3rd prize in the Academy’s creative competition

  * Based on Arduino UNO, programed the main function codes 

* Designing a finger-guessing game (MATLAB) (Sep 2016 - Nov 2016)

  * Programed the MATLAB project which enabled predicting the results of finger-guessing game by distinguishing input pictures

  * Improved the algorithm to attain more accurate results through machine learning. 
  
# ADDITIONAL

* Technical Skills: Python, R, Tableau, C, MySQL, JMP, SAS, Arduino, MATLAB, 

* Language fluency: Mandarin, English

* Co-Curricular Activity: Deputy Head of Student Union (Xiamen University) 

* Volunteer work: Volunteered at Global BRICS Conference in Xiamen (2017)

* Work Authorization: Singapore (Internship), China (Citizen)

* Interests: Photography, image editing
